version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
      - websocket
    restart: unless-stopped
  
  web:
    build: .
    container_name: final-backend-http
    command: gunicorn config.wsgi:application -b 0.0.0.0:8000 --workers 4
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - redis

  websocket:
    build: .
    container_name: final-backend-websocket
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    volumes:
      - .:/app
    expose:
      - "8001"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"